### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by xiPakuL** [SirEndii/Lua-Projects#2]
The scripts have serveral errors in 1.19.2
would be cool if you specified a target version or smh

**Comment by SirEndii** [comment]
Define "errors"
And for which AP version?

**Comment by xiPakuL** [comment]
my bad, if it doesn't find it's monitor it errors out weirdly.

**Comment by xiPakuL** [comment]
close

**Comment by SirEndii** [comment]
Alright, I will try to improve that anyways in the future
